In [2]:
import numpy as np

In [161]:
class Data:
    max_depth = 15
    empty_val = np.nan

    def __init__(self):
        self.names = []
        self.record_times = np.zeros((Data.max_depth,1))
        self.values = np.empty((Data.max_depth,0))
        self.depth = 0
        self.time_cur = 0
        
    def put(self, time, name, val):

        if name not in self.names:
            self.names.append(name)
            self.depth = 1
            param_val = np.zeros((Data.max_depth, 1))
            self.values = np.concatenate((self.values, param_val), axis=1)

        index_val = self.names.index(name)

        if time > self.time_cur:
            self.record_times = Data.shift(self.record_times, -1, Data.empty_val) 
            self.record_times[Data.max_depth - 1] = time
            self.time_cur = time
            self.values = Data.shift(self.values, -1, Data.empty_val)
            self.values[Data.max_depth - 1, index_val] = val
            self.depth += 1
        elif time == self.time_cur:
            self.values[Data.max_depth - 1, index_val] = val

    @staticmethod
    def shift(arr, num, fill_value=np.nan):
        result = np.empty_like(arr)
        if num > 0:
            result[:num] = fill_value
            result[num:] = arr[:-num]
        elif num < 0:
            result[num:] = fill_value
            result[:num] = arr[-num:]
        else:
            result = arr
        return result

In [162]:
data = Data()

In [163]:
data.values

array([], shape=(15, 0), dtype=float64)

In [166]:
data.record_times

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.],
       [7.],
       [8.],
       [9.]])

In [103]:
#data.put(0,"Tp2", 10)

In [104]:
data.values

array([], shape=(15, 0), dtype=float64)

In [165]:
for i in range(1,10):
    data.put(i,"Tp2", 100+i)
    if (i>5):
        data.put(i,"To2", 100+i)
    print(np.concatenate((data.values,data.record_times), axis = 1))    

[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [101.   1.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [101.   1.]
 [102.   2.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [101.   1.]
 [102.   2.]
 [103.   3.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [101.   1.]
 [102.   2.]
 [103.   3.]
 [104.   4.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [101.   1.]
 [102.   2.]
 [103.   3.]
 [104.   4.]
 [105.   5.]]
[[  0.   0.   0.]
 [

In [167]:
data.values

array([[  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [101.,   0.],
       [102.,   0.],
       [103.,   0.],
       [104.,   0.],
       [105.,   0.],
       [106., 106.],
       [107., 107.],
       [108., 108.],
       [109., 109.]])

In [168]:
data.record_times

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.],
       [6.],
       [7.],
       [8.],
       [9.]])

In [169]:
data.names

['Tp2', 'To2']